# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true


# Mod properties
mod_version = 2.0.0
maven_group = top.leonx.dynlight
archives_name = CreateDynamicLightsUnofficial
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1
parchment_version = 2023.09.03

# Dependencies
fabric_loader_version = 0.16.0
fabric_api_version = 0.92.2+1.20.1
forge_version = 1.20.1-47.3.3
architectury_api_version = 9.2.14

# Forge dependencies
create_forge_version = 6.0.8-289
ponder_forge_version = 1.0.91
flywheel_forge_version = 1.0.5
registrate_version = MC1.20-1.3.3
embeddium_version = 0.3.30
oculus_version = 1.20.1-1.8.0
dynamiclights_forge_version = forge-1.20.1-1.0.10
ryoamiclights_forge_version = c2Th4NIB
obsidianui_version = 0.2.1+mc1.20.1

# Fabric dependencies
create_fabric_version = 6.0.8.1+build.1744-mc1.20.1
flywheel_fabric_version = 1.0.5
sodium_version = 0.5.13
dynamiclights_fabric_version = fabric-1.20.1-1.0.10
ryoamiclights_fabric_version = VTzHz71U
indium_version = 1.0.36
iris_version = 1.7.6
modmenu_version = 7.2.2
forgeconfigapiport_fabric_version = 8.0.0
